const { KasaEdition, PrismaClient, PlanType } = require("@prisma/client");
const bcrypt = require("bcryptjs");
const crypto = require("crypto");

const prisma = new PrismaClient();

function sha256(value) {
  return crypto.createHash("sha256").update(value).digest("hex");
}

function createLicenseKey(productPrefix = "KASA") {
  const cleanPrefix = productPrefix
    .toUpperCase()
    .replace(/[^A-Z0-9-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 24) || "KASA";
  const segments = Array.from({ length: 4 }, () =>
    crypto.randomBytes(3).toString("hex").toUpperCase(),
  );
  return `${cleanPrefix}-${segments.join("-")}`;
}

function previewLicenseKey(key) {
  const parts = key.split("-");
  return `${parts[0]}-${parts[1]}-****-****-${parts[4]}`;
}

function getEncryptionKey() {
  const secret = process.env.LICENSE_SIGNING_SECRET || process.env.SESSION_SECRET;
  if (!secret || secret.length < 24) {
    throw new Error("LICENSE_SIGNING_SECRET must be at least 24 characters long.");
  }

  return crypto.createHash("sha256").update(secret).digest();
}

function encryptLicenseKey(key) {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", getEncryptionKey(), iv);
  const encrypted = Buffer.concat([cipher.update(key.trim().toUpperCase(), "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return [iv, tag, encrypted].map((part) => part.toString("base64url")).join(".");
}

async function upsertLicense({
  productId,
  edition,
  buyerName,
  buyerEmail,
  platform,
  purchaseRef,
  maxActivations,
  saleAmount,
  saleChannel,
  marketingSource,
}) {
  const existing = await prisma.license.findFirst({
    where: { buyerEmail, productId },
  });

  if (existing) return null;

  const key = createLicenseKey(`KASA-${edition}`);
  await prisma.license.create({
    data: {
      productId,
      keyHash: sha256(key),
      keyPreview: previewLicenseKey(key),
      keyEncrypted: encryptLicenseKey(key),
      buyerName,
      buyerEmail,
      platform,
      purchaseRef,
      saleAmount,
      saleCurrency: "INR",
      saleChannel,
      marketingSource,
      soldAt: new Date(),
      edition,
      plan: PlanType.LIFETIME,
      maxActivations,
      notes: "Demo licence generated by seed.",
    },
  });

  return key;
}

async function main() {
  const passwordHash = await bcrypt.hash("Password@123", 12);
  await prisma.adminUser.upsert({
    where: { email: "admin@kasa.test" },
    update: {},
    create: {
      name: "Kasa Admin",
      email: "admin@kasa.test",
      passwordHash,
    },
  });

  const enterprise = await prisma.product.upsert({
    where: { slug: "kasa-enterprise" },
    update: {},
    create: {
      name: "Kasa Enterprise",
      slug: "kasa-enterprise",
      description: "Full LMS, live classes, exams, certificates, notifications, and marketplace-ready modules.",
    },
  });

  const starter = await prisma.product.upsert({
    where: { slug: "kasa-starter-kit" },
    update: {},
    create: {
      name: "Kasa Starter Kit",
      slug: "kasa-starter-kit",
      description: "A focused starter edition for smaller academies and quick launches.",
    },
  });

  const generatedKeys = [];
  const enterpriseKey = await upsertLicense({
    productId: enterprise.id,
    edition: KasaEdition.ENTERPRISE,
    buyerName: "Demo Academy",
    buyerEmail: "buyer.enterprise@kasa.test",
    platform: "direct",
    purchaseRef: "DEMO-ENT-001",
    maxActivations: 1,
    saleAmount: 49999,
    saleChannel: "direct-website",
    marketingSource: "demo-seed",
  });
  if (enterpriseKey) generatedKeys.push(["Kasa Enterprise", enterpriseKey]);

  const starterKey = await upsertLicense({
    productId: starter.id,
    edition: KasaEdition.STARTER,
    buyerName: "Starter Buyer",
    buyerEmail: "buyer.starter@kasa.test",
    platform: "envato",
    purchaseRef: "DEMO-STK-001",
    maxActivations: 2,
    saleAmount: 9999,
    saleChannel: "envato",
    marketingSource: "marketplace",
  });
  if (starterKey) generatedKeys.push(["Kasa Starter Kit", starterKey]);

  console.log("\nSeed complete.");
  console.log("Admin login: admin@kasa.test / Password@123");
  if (generatedKeys.length) {
    console.log("\nGenerated demo licence keys:");
    for (const [product, key] of generatedKeys) {
      console.log(`- ${product}: ${key}`);
    }
  } else {
    console.log("Demo licences already exist. Existing full keys cannot be displayed because only hashes are stored.");
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
