const { PrismaClient, PlanType } = require("@prisma/client");
const bcrypt = require("bcryptjs");
const crypto = require("crypto");

const prisma = new PrismaClient();

function sha256(value) {
  return crypto.createHash("sha256").update(value).digest("hex");
}

function createLicenseKey(productPrefix = "KASA") {
  const segments = Array.from({ length: 4 }, () =>
    crypto.randomBytes(2).toString("hex").toUpperCase(),
  );
  return `${productPrefix}-${segments.join("-")}`;
}

function previewLicenseKey(key) {
  const parts = key.split("-");
  return `${parts[0]}-${parts[1]}-****-****-${parts[4]}`;
}

async function upsertLicense({ productId, productPrefix, buyerName, buyerEmail, platform, purchaseRef, maxActivations }) {
  const existing = await prisma.license.findFirst({
    where: { buyerEmail, productId },
  });

  if (existing) return null;

  const key = createLicenseKey(productPrefix);
  await prisma.license.create({
    data: {
      productId,
      keyHash: sha256(key),
      keyPreview: previewLicenseKey(key),
      buyerName,
      buyerEmail,
      platform,
      purchaseRef,
      plan: PlanType.LIFETIME,
      maxActivations,
      notes: "Demo licence generated by seed.",
    },
  });

  return key;
}

async function main() {
  const passwordHash = await bcrypt.hash("Password@123", 12);
  await prisma.adminUser.upsert({
    where: { email: "admin@kasa.test" },
    update: {},
    create: {
      name: "Kasa Admin",
      email: "admin@kasa.test",
      passwordHash,
    },
  });

  const enterprise = await prisma.product.upsert({
    where: { slug: "kasa-enterprise" },
    update: {},
    create: {
      name: "Kasa Enterprise",
      slug: "kasa-enterprise",
      description: "Full LMS, live classes, exams, certificates, notifications, and marketplace-ready modules.",
    },
  });

  const starter = await prisma.product.upsert({
    where: { slug: "kasa-starter-kit" },
    update: {},
    create: {
      name: "Kasa Starter Kit",
      slug: "kasa-starter-kit",
      description: "A focused starter edition for smaller academies and quick launches.",
    },
  });

  const generatedKeys = [];
  const enterpriseKey = await upsertLicense({
    productId: enterprise.id,
    productPrefix: "KENT",
    buyerName: "Demo Academy",
    buyerEmail: "buyer.enterprise@kasa.test",
    platform: "direct",
    purchaseRef: "DEMO-ENT-001",
    maxActivations: 1,
  });
  if (enterpriseKey) generatedKeys.push(["Kasa Enterprise", enterpriseKey]);

  const starterKey = await upsertLicense({
    productId: starter.id,
    productPrefix: "KSTK",
    buyerName: "Starter Buyer",
    buyerEmail: "buyer.starter@kasa.test",
    platform: "envato",
    purchaseRef: "DEMO-STK-001",
    maxActivations: 2,
  });
  if (starterKey) generatedKeys.push(["Kasa Starter Kit", starterKey]);

  console.log("\nSeed complete.");
  console.log("Admin login: admin@kasa.test / Password@123");
  if (generatedKeys.length) {
    console.log("\nGenerated demo licence keys:");
    for (const [product, key] of generatedKeys) {
      console.log(`- ${product}: ${key}`);
    }
  } else {
    console.log("Demo licences already exist. Existing full keys cannot be displayed because only hashes are stored.");
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
